### ISSUE TITLE
As an Endowment manager, I want to decide who (multi-sig or delegate) governs which parameters of my Endowment

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1708] opened 2023-02-06 00:33 UTC
**CU Ticket:** https://app.clickup.com/t/865bm380x
**Assigned To:** 
**Version:** v1.8

## COS
- [ ] styling matches Figma
- [ ] User can change the controlling entity/delegate wallet for various settings fields (if the `SettingsPermissions.modifiable == `true``)
- [ ] Hitting "Submit changes" creates a proposal to the Endowment multisig to send the correct update settings 

# Fetching the Settings Controller for an Endowment
You will need to query the Account Settings Controller contract endpoint: 
```rust
endowment_controller { id: u32 }
``` 

This will provide you with an `EndowmentController` struct for a reply, with `SettingsPermissions` struct for each settings field (ie. a row in the settings management table you're building here): 
```rust
pub struct EndowmentController {
    pub endowment_controller: SettingsPermissions,
    pub beneficiaries_allowlist: SettingsPermissions,
    pub contributors_allowlist: SettingsPermissions,
    pub maturity_allowlist: SettingsPermissions,
    pub donation_match_active: SettingsPermissions,
    pub earnings_fee: SettingsPermissions,
    pub withdraw_fee: SettingsPermissions,
    pub deposit_fee: SettingsPermissions,
    pub aum_fee: SettingsPermissions,
    pub kyc_donors_only: SettingsPermissions,
    pub name: SettingsPermissions,
    pub image: SettingsPermissions,
    pub logo: SettingsPermissions,
    pub categories: SettingsPermissions,
    pub ignore_user_splits: SettingsPermissions,
    pub split_to_liquid: SettingsPermissions,
}
```

The `SettingsPermissions` payload will have the following shape: 
```rust
pub struct SettingsPermissions {
    owner_controlled: bool,  // CW3 Multisig Owner
    gov_controlled: bool, // SubDao Gov
    modifiable: bool, // Might not be updatable (this is the "locked forever" setting when set to `true`)
    delegate: Option<Delegate>, 
}
```
The Delegate struct looks like: 
```rust
pub struct Delegate {
    address: Addr,
    expires: Option<u64>, // datetime int of delegation expiry
}
```

# Updating the Endowment Settings Controller
Only the user/entity set as the "controller" for the field `endowment_controller` in the SettingsPermissions is allowed to update the settings controller as a whole(ie. to submit on this page). The other individual settings fields/rows tells us who can change/update individual Endowment Settings items within `EndowmentSettings` (a separate struct). This page is concerned with updating the whole Permissions. 

To do so, we pass a proposal (if a CW3 multisig or Gov contract controls the SettingsController field), or directly should a delegate address control it, containing the following message to the accounts settings controller contract: `update_endowment_controller(UpdateEndowmentControllerMsg)`. The message need only send along fields that have changed. 
 
```rust
pub struct UpdateEndowmentControllerMsg {
    pub id: u32,
    pub endowment_controller: Option<SettingsPermissions>,
    pub name: Option<SettingsPermissions>,
    pub image: Option<SettingsPermissions>,
    pub logo: Option<SettingsPermissions>,
    pub categories: Option<SettingsPermissions>,
    pub kyc_donors_only: Option<SettingsPermissions>,
    pub split_to_liquid: Option<SettingsPermissions>,
    pub ignore_user_splits: Option<SettingsPermissions>,
    pub donation_match_active: Option<SettingsPermissions>,
    pub beneficiaries_allowlist: Option<SettingsPermissions>,
    pub contributors_allowlist: Option<SettingsPermissions>,
    pub maturity_allowlist: Option<SettingsPermissions>,
    pub earnings_fee: Option<SettingsPermissions>,
    pub deposit_fee: Option<SettingsPermissions>,
    pub withdraw_fee: Option<SettingsPermissions>,
    pub aum_fee: Option<SettingsPermissions>,
}
```

**Comment by misicnenad** [comment] 2023-03-07 08:29
Figma https://www.figma.com/file/sDjoeJ2IFPd9EJ1LI2WMvF/Product-Design?node-id=3079%3A205143&t=BZo9HoyAgJxrH6nf-0

**Comment by misicnenad** [comment] 2023-03-07 13:55
> Please ignore the "Lock Forever" column

@SovereignAndrey if I understood this correctly, this column shouldn't yet be added to the table at all?

**Comment by misicnenad** [comment] 2023-03-07 14:13
@SovereignAndrey can any permission be given to more than one entity at the same time, e.g. both to "ADMIN WALLET" and "DELEGATE" (i.e. treat this as a checkbox)? Or is this a plain radio button with only one value being selectable at a time?

**Comment by SovereignAndrey** [comment] 2023-03-08 01:04
> @SovereignAndrey can any permission be given to more than one entity at the same time, e.g. both to "ADMIN WALLET" and "DELEGATE" (i.e. treat this as a checkbox)? Or is this a plain radio button with only one value being selectable at a time?

It should be a radio button, so only 1. Delegate address field should be grayed out if that radio option is not selected.

**Comment by misicnenad** [comment] 2023-03-08 14:33
> It should be a radio button, so only 1. Delegate address field should be grayed out if that radio option is not selected.

@SovereignAndrey so delegate address field is actually an input field?

**Comment by SovereignAndrey** [comment] 2023-03-09 00:07
> @SovereignAndrey so delegate address field is actually an input field?

Yes, it takes a wallet address.

> - Is there an existing endpoint/API we can use to fetch the permissions?

100% Contract driven from queries to updating. No AWS involvement here. You will need to query the Account Settings Controller contract endpoint: `endowment_settings { id: <endow_id> }`

> - Is the list of permissions fixed or will it possibly be expanded/contracted in the future?

Sure. It might change if the contract's settings controller struct changes.

> - Selecting "delegate" as permission option enables the "delegate address" input field - selecting any other disables it. If the user inserts some value in the "delegate address" field, but later selects some other permission option (e.g. changes from "delegate" to "governance"), is it ok if the submitted form includes the previously inserted delegate address (i.e. will it be automatically ignored in the backend)

There's a lot of nuance to how we should display this I think, since if the connected wallet is not a delegate then they cannot change that field once control has been delegated away. (ie. We ought to disable the radio button if they are not the currently set controller for a field)

We would only want to allow changing of and to pass for updating only a subset of  changed fields which are editable by the current controlling entity(gov / multisig via a proposal) or delegate wallet doing the sending.

**Comment by misicnenad** [comment] 2023-03-09 06:20
> There's a lot of nuance to how we should display this I think, since if the connected wallet is not a controlling delegate then they cannot change that field once control has been delegated away.

Once the control is delegated away (and the change submitted), with regards to the user who is now no longer the controlling entity, it might be easiest from implementation perspective to either:
1. Hide the setting from this user completely (only show the setting to the "controlling" user)
2. Gray the setting out for the non-controlling user

It would basically mean that:
- the backend always returns all permission settings
- the webapp controls who sees and has access to what
- **the backend would still need to validate that the request to update the setting is done by a user (wallet) which has the permission to do so.**

> If it's changed to something else than a Delegate that would be an `null` value and there'd be nothing to display for the address input.

So if I understood you correctly, for this flow:
- user selects "Delegate" -> "delegate address" input field is enabled
- user inputs some valid wallet address
- user selects something other than "Delegate"

The "delegate address" field would not only become disabled, but also its value would become `null` (thus deleting any previously inserted value), is that right? 
Would that also mean that submitting the "delegate address" field with a value, but with e.g. "Governance" set as the permissioned entity, the contracts would view that as an invalid submission (i.e. "delegate address" can have a value *only* if "Delegate" is selected, otherwise it *must* be set to `null`)?

**Comment by SovereignAndrey** [comment] 2023-03-09 07:02
> the backend always returns all permission settings
the webapp controls who sees and has access to what setting
the backend would still need to validate that the request to update the setting is done by a user (wallet) which has the permission to do so.

@misicnenad Yes, that makes sense, the web app can manage who sees what as needed. The smart contract will handle checking that the wallet/contract sending the update messages is allowed to do so.

> Once the control is delegated away (and the change submitted), with regards to the user who is now no longer the controlling entity, it might be easiest from implementation perspective to either

Since this table / page view is about changing the SettingsController as a whole, we can simple show this view as read-only (disabled radios / inputs and no submission button) for non-authorized users. This allows people to see who controls what parts of the Endowment. 

> Would that also mean that submitting the "delegate address" field with a value, but with e.g. "Governance" set as the permissioned entity, the contracts would view that as an invalid submission (i.e. "delegate address" can have a value only if "Delegate" is selected, otherwise it must be set to null)?

Had to double check the code. There *can* be a Delegate set as well as a Owner / Gov. The current UI is mis-leading since it suggests that delegating removes the original owners rights, which it does not. Additionally, because those fields are boolean for Owner and Gov they could both, in theory, have control over something (in addition to a Delegate wallet if setup too!). **Checkboxes or on/off toggles are probably more appropriate representation. **

Once a delegate is set (on one or more fields) it can be submitted along with any other changes to the fields from the user that has control over the `endowment_controller` field.

**Comment by misicnenad** [comment] 2023-03-09 08:20
@SovereignAndrey 
> There can be a Delegate set as well as a Owner / Gov. The current UI is mis-leading since it suggests that delegating removes the original owners rights, which it does not. Additionally, because those fields are boolean for Owner and Gov they could both, in theory, have control over something (in addition to a Delegate wallet if setup too!). Checkboxes or on/off toggles are probably more appropriate representation.

Clear. Will update the code accordingly.

> Once a delegate is set (on one or more fields) it can be submitted along with any other changes to the fields from the user that has control over the endowment_controller field.

But if the delegate is **not** set then the "delegate address" field must be `null`?

**Comment by SovereignAndrey** [comment] 2023-03-09 08:27
> But if the delegate is **not** set then the "delegate address" field must be `null`?

@misicnenad If there is no delegate set, then then `delegate` field in  `SettingsPermissions` would be null/undefined instead of populated by the `Delegate` struct.

**Comment by misicnenad** [comment] 2023-03-09 08:49
@SovereignAndrey 

> pub struct SettingsPermissions {
    owner_controlled: bool,  // CW3 Multisig Owner
    gov_controlled: bool, // SubDao Gov
    modifiable: bool, // Might not be updatable (this is the "locked forever" setting when set to `true`)
    delegate: Option<Delegate>, 
}

I see now, the `delegate` is not a `bool` like the others, so if it is *not* checked in the table, the "delegate address" field would not be set in the `settings.delegate.address` field or in other words, `settings.delegate === null`.

**Comment by misicnenad** [comment] 2023-03-09 11:04
> pub struct UpdateEndowmentControllerMsg {
    pub id: u32,
    pub endowment_controller: Option<SettingsPermissions>,
    pub name: Option<SettingsPermissions>,
    pub image: Option<SettingsPermissions>,
    pub logo: Option<SettingsPermissions>,
    pub categories: Option<SettingsPermissions>,
    pub kyc_donors_only: Option<SettingsPermissions>,
    pub split_to_liquid: Option<SettingsPermissions>,
    pub ignore_user_splits: Option<SettingsPermissions>,
    pub donation_match_active: Option<SettingsPermissions>,
    pub beneficiaries_allowlist: Option<SettingsPermissions>,
    pub contributors_allowlist: Option<SettingsPermissions>,
    pub maturity_allowlist: Option<SettingsPermissions>,
    pub earnings_fee: Option<SettingsPermissions>,
    pub deposit_fee: Option<SettingsPermissions>,
    pub withdraw_fee: Option<SettingsPermissions>,
    pub aum_fee: Option<SettingsPermissions>,
}

Just to check if I understand the meaning of each of these fields and how they correspond to the table rows:
- `id` - what is this ID referring to, ID of endowment? ID of controller?
- `endowment_controller` - who can update any of the controller params, corresponds to `Changes to Admin Wallet members`
- `name, image, logo, categories, kyc_donors_only` - all grouped under `Changes to profile` (they should have the same permissions set as that table row), no specific rows for each individual setting
- `split_to_liquid` - which table row does this correspond to?
- `ignore_user_splits` - which table row does this correspond to?
- `donation_match_active` - which table row does this correspond to?
- `beneficiaries_allowlist` - corresponds to `Changes to beneficiaries whitelist`
- `contributors_allowlist` - corresponds to `Changes to contributors whitelist` 
- `maturity_allowlist` - which table row does this correspond to?
- `earnings_fee, deposit_fee, withdraw_fee, aum_fee` - corresponds to `Changes to Admin Wallet parameters`

Please clarify the fields for which no match was given above.
Is my understanding of the other fields correct? 

Table is below for easier visibility of available rows.
![image](https://user-images.githubusercontent.com/19427053/224002995-b535f91a-8214-429f-862e-54c3c17e652a.png)

**Comment by SovereignAndrey** [comment] 2023-03-09 11:36
> * `id` - **what is this ID referring to, ID of endowment? ID of controller?**

Endowment ID

> * `split_to_liquid` - **which table row does this correspond to?**
> * `ignore_user_splits` - **which table row does this correspond to?**

These two need to be own row: `Changes to donation split parameters`

> * `donation_match_active` - **which table row does this correspond to?**

Needs to be it's own row, but we can leave off for now and add in later once we have Donation Matching ready. Every endowment would have it off for now anyways. 

> * `maturity_allowlist` - **which table row does this correspond to?** 

Tied in w/ beneficiaries allowlist, just after the maturity point has been reached. 

> * `earnings_fee, deposit_fee, withdraw_fee, aum_fee` - corresponds to `Changes to Admin Wallet parameters`

These would fall under a row called: `Changes to account fees`

> * **RELATED: how to pass the settings for `Liquid account withdrawals` and `Locked account withdrawals`?**

Don't. :) We remove those rows for now. 

> 
> Please clarify the fields for which no match was given above. Is my understanding of the other fields correct?

Remove the two rows on Investment strategies. Those don't exist on the new `v2.1.0` contracts. I think you're OK for the rest.

**Comment by SovereignAndrey** [comment] 2023-03-09 11:56
> > modifiable: bool, // Might not be updatable (this is the "locked forever" setting when set to `true`)
> 
> This field's expected behavior is a bit unclear. When is the `modifiable: bool` field itself ever "modifiable"?
> If it's once set to `false`, can it ever be switched back to `true`?

If a field is ever set to false then it is forever set that way. It cannot be modified anymore by anyone. If modifiable == true then authorized users can update that field as needed.

**Comment by misicnenad** [comment] 2023-03-10 10:54
@SovereignAndrey @lambi9891 

> There can be a Delegate set as well as a Owner / Gov. The current UI is mis-leading since it suggests that delegating removes the original owners rights, which it does not. Additionally, because those fields are boolean for Owner and Gov they could both, in theory, have control over something (in addition to a Delegate wallet if setup too!). Checkboxes or on/off toggles are probably more appropriate representation.

In light of new requirements from quote above (see original https://github.com/AngelProtocolFinance/angelprotocol-web-app/issues/1708#issuecomment-1461434109), instead of using radio buttons (which indicate only **one** option can be selected at one time) we could use checkboxes (which indicate that multiple options can be selected at the same time):

Radio buttons (as per Figma):
![image](https://user-images.githubusercontent.com/19427053/224254944-4d069be5-9fd9-4066-bc34-615fc64c974e.png)
Checkboxes:
![image](https://user-images.githubusercontent.com/19427053/224297201-5ca9572a-b8ec-4f70-accb-6d08ebcf113e.png)

Here's a sample row in light mode as well
![image](https://user-images.githubusercontent.com/19427053/224297374-1b9ca91e-cf3b-4635-bef6-41927d2ef9d3.png)

You can see the first checkbox is checked as has an orange background with a white "check" icon, the second checkbox is checked and focused and has an additional light orange ring around it to indicate that, while the third one not checked, so it has just a light gray border (aligned with other border colors we generally use).

I'd even propose we use this style of checkboxes throughout the webapp.
Current checkboxes (checked + focused, just checked, unchecked):
![image](https://user-images.githubusercontent.com/19427053/224297970-aab38e00-2114-4843-897f-7e895751bba3.png)
![image](https://user-images.githubusercontent.com/19427053/224297924-8f68099f-67ae-4074-84cd-4f794a9096ef.png)

Proposed checkboxes (checked + focused, just checked, unchecked):
![image](https://user-images.githubusercontent.com/19427053/224298041-8a212c62-4279-4ffe-a6d9-9be2b04e30e1.png)
![image](https://user-images.githubusercontent.com/19427053/224298073-017f13a6-87da-4aec-a7ed-e294ed419c48.png)

**Comment by misicnenad** [comment] 2023-03-10 11:13
> If a field is ever set to false then it is forever set that way. It cannot be modified anymore by anyone. If modifiable == true then authorized users can update that field as needed.

@SovereignAndrey do we then include the "Actions" column (with the "Lock Forever" btn) in this PR, the logic is there, right?

**Comment by SovereignAndrey** [comment] 2023-03-10 11:33
> > If a field is ever set to false then it is forever set that way. It cannot be modified anymore by anyone. If modifiable == true then authorized users can update that field as needed.
> 
> @SovereignAndrey do we then include the "Actions" column (with the "Lock Forever" btn) in this PR, the logic is there, right?
> ![image](https://user-images.githubusercontent.com/19427053/224301925-46570666-472e-4ed6-9b0e-0e420906d2b1.png)
> 

Yes, for the charities we can just hide the column since those are always locked forever.

**Comment by misicnenad** [comment] 2023-03-10 11:40
@SovereignAndrey @lambi9891 just in case you miss the big checkbox question https://github.com/AngelProtocolFinance/angelprotocol-web-app/issues/1708#issuecomment-1463628336

**Comment by SovereignAndrey** [comment] 2023-03-10 12:26
> Proposed checkboxes (checked + focused, just checked, unchecked):
> ![image](https://user-images.githubusercontent.com/19427053/224298041-8a212c62-4279-4ffe-a6d9-9be2b04e30e1.png)
> ![image](https://user-images.githubusercontent.com/19427053/224298073-017f13a6-87da-4aec-a7ed

I think it looks good. 👍 Separate PR to handle switching over the rest of the checkboxes though.

**Comment by lambi9891** [comment] 2023-03-12 16:33
ok for mee too

**Comment by misicnenad** [comment] 2023-03-13 07:50
@SovereignAndrey 

> > * `earnings_fee, deposit_fee, withdraw_fee, aum_fee` - corresponds to `Changes to Admin Wallet parameters`
> 
> These would fall under a row called: `Changes to account fees`

So basically, when querying the endowment controller endpoint (and with regards to the `"Changes to account fees"` table row), we can assume that all of those fields will have the same subfield values, i.e. all will have the same `modifiable`, the same `gov_controlled` etc?

**Comment by misicnenad** [comment] 2023-03-13 08:36
@SovereignAndrey 
> Updating the Endowment Settings Controller

To update the endowment permission settings, do we send an update msg directly to contract or do we send it to AWS (use it as proxy as usual)?

**Comment by misicnenad** [comment] 2023-03-13 09:00
@SovereignAndrey 

>Only the user/entity set as the "controller" for the field endowment_controller in the SettingsPermissions is allowed to update the settings controller as a whole(ie. to submit on this page). The other individual settings fields/rows tells us who can change/update individual Endowment Settings items within EndowmentSettings (a separate struct). This page is concerned with updating the whole Permissions.
>
> To do so, we pass a proposal (if a CW3 multisig or Gov contract controls the SettingsController field), or directly should a delegate address control it, containing the following message to the accounts settings controller contract: update_endowment_controller(UpdateEndowmentControllerMsg). The message need only send along fields that have changed.

Basically this means:
- if CW3 multisig or Gov contract controls the SettingsController field, then we create a proposal msg containing the `update_endowment_controller` msg (similar how we do for e.g. [updating funds](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/RC-v1.8/src/pages/Admin/Core/Templates/index-fund/Members/useUpdateFund.ts#L67))
- if a delegate address controls the SettingsController field, we just send the `update_endowment_controller` msg directly to the account settings controller contract.

Is my understanding correct?

**Comment by misicnenad** [comment] 2023-03-13 11:46
@SovereignAndrey even though "Governance" column shouldn't be displayed to charities, when querying for their permission settings, the appropriate `gov_controller: bool` fields will still be present (not `undefined` or `null`)?
Also, charities' field `modifiable` will always have its value set to `false`?

**Comment by SovereignAndrey** [comment] 2023-03-13 23:45
> @SovereignAndrey 
> 1. Even though "Governance" column shouldn't be displayed to charities, when querying for their permission settings, the appropriate `gov_controller: bool` fields will still be present (not `undefined` or `null`)?
> 2. We will have separate webapps for charities and for AIFs (normal endows), right? 
> 3. Charities' field `modifiable` will always have its value set to `false`?

1. Yes
2. Yep
3. Correct

**Comment by SovereignAndrey** [comment] 2023-03-14 10:25
> @SovereignAndrey one more clarification needed before creating PR - need to confirm who is allowed to modify permission settings. Let's say wallet A is connected:
> 
> 1. if permission is `owner_controlled` -> wallet A is allowed to modify settings if it is the owner of the endowment whose settings are displayed?
> 2. if permission set to `gov_controlled` -> same as above?
> 3. if permission set to `delegate` -> wallet A is allowed to modify settings only if its address is the same as set in the `delegate address` field?
> 4. **no other user is allowed to modify any of the settings**, no matter the `modifiable` field value?

1. Wallet A can modify settings if it is a member of the CW3 multisig that is the owner of the Endowment. 
2. Gov is a governance contract so that's a trickier one (prob not something that would every really be done via UI, but let me think about it). More likely, if the connected wallet is a staking member on the Gov SubDao contract, but again way more complicated to check. 
3. Yes, if delegate then check if connected wallet == delegate address. 
4. Correct.

**Comment by misicnenad** [comment] 2023-03-14 10:44
> > @SovereignAndrey one more clarification needed before creating PR - need to confirm who is allowed to modify permission settings. Let's say wallet A is connected:
> > 
> > 1. if permission is `owner_controlled` -> wallet A is allowed to modify settings if it is the owner of the endowment whose settings are displayed?
> > 2. if permission set to `gov_controlled` -> same as above?
> > 3. if permission set to `delegate` -> wallet A is allowed to modify settings only if its address is the same as set in the `delegate address` field?
> > 4. **no other user is allowed to modify any of the settings**, no matter the `modifiable` field value?
> 
> 1. Wallet A can modify settings if it is a member of the CW3 multisig that is the owner of the Endowment.
> 2. Gov is a governance contract so that's a trickier one (prob not something that would every really be done via UI, but let me think about it). More likely, if the connected wallet is a staking member on the Gov SubDao contract, but again way more complicated to check.
> 3. Yes, if delegate then check if connected wallet == delegate address.
> 4. Correct.

@SovereignAndrey 
Will be handling just all except 2. (gov-related) for now.

**Comment by misicnenad** [comment] 2023-03-15 05:57
> **UPDATE:** `profile` is removed now from the controller and update msg struct & `donation_match_active` has been added to both. The "profile related" fields (ie. `kyc_donors_only, name, image, logo, categories`) have had the default values changed for Charity type endowments so that they ARE modifiable should they choose to do so. Also, fees are moved from their own update endpoint into the main endowment settings update endpoint.

Source: https://github.com/AngelProtocolFinance/angelprotocol-web-app/pull/1885#discussion_r1136542785

**Comment by misicnenad** [comment] 2023-03-15 07:55
@SovereignAndrey

> Only the user/entity set as the "controller" for the field endowment_controller in the SettingsPermissions is allowed to update the settings controller as a whole(ie. to submit on this page). The other individual settings fields/rows tells us who can change/update individual Endowment Settings items within EndowmentSettings (a separate struct). This page is concerned with updating the whole Permissions.
>
> To do so, we pass a proposal (if a CW3 multisig or Gov contract controls the SettingsController field), or directly should a delegate address control it, containing the following message to the accounts settings controller contract: update_endowment_controller(UpdateEndowmentControllerMsg). The message need only send along fields that have changed.

Been thinking about this and I think I had a different understanding of the requirements than was intended.
So this is the basic pseudo-code for updating the controller (which assumes the user is authorized to make any changes at all):

```ts
if (
  cw3_multisig_or_gov_contract_controls_the_field &&
  connected_wallet === Endowment.owner
) {
  create_a_proposal();
} /** if delegate address controls it */ else {
  send_directly_to_contract();
}
```

My (possibly wrong) understanding was that depending on the satisfied condition, **all fields should either be sent as a proposal or as a direct msg to contract**. But upon further thought, I came to a realization that there might be a piece of (pseudo-)code missing.
Below is the full code:

```ts
for (field of all_changed_fields) {
  if (
    (field.owner_controlled || field.gov_controlled) &&
    (connected_wallet === EndowmentController.endowment_controller.delegate ||
      connected_wallet === Endowment.owner)
  ) {
    create_a_proposal_just_for_this_field();
  } /** if delegate address controls it */ else {
    send_directly_to_contract_just_for_this_field();
  }
}
```

This basically means that we should check for each field which condition is satisfied and based on that send `changed_fields.length` proposals/msgs. This could be optimized of course, e.g. if there's a same delegate for multiple fields, all those fields would be sent as part of a single msg. Is my understanding correct?

Need to confirm with you the **exact conditions and flows** to send these messages and which type of message (proposal VS direct msg) is sent. Some of the questions might be redundant, but it is apparent that we need to have this clarified in great detail. I'll list the questions first and then list all the cases that pop to mind for which those same questions need to be answered.

**NOTE: "User" === "Wallet" === "Wallet address"**

The questions are:

1. Which fields can they update? If any, read further.
2. Can they update a setting when `settings.modifiable === false` for that same setting?
3. What is sent if `settings.owner_controlled` is selected for a specific setting?
4. What is sent if `settings.gov_controlled` is selected for a specific setting?
5. What is sent if `settings.delegate` (+ `delegate_address`) is selected for a specific setting (and the User is not the one delegated to)?
6. What is sent if any combination of `owner_controlled`, `gov_controlled` and `delegate(.address)` is selected? Any edge cases?

The cases are:

1. User is just `Endowment.owner` ([link to example type](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/RC-v1.8/src/types/contracts/account.ts#L57)).
2. User is just `EndowmentController.endowment_controller.delegate`.
3. User is just `EndowmentController.{settings_field}.delegate.address` for the field being changed.
4. User is both `Endowment.owner` and `EndowmentController.endowment_controller.delegate`.
5. User is both `Endowment.owner` and `EndowmentController.{settings_field}.delegate.address` for the field being changed.
6. User is both `EndowmentController.endowment_controller.delegate` and `EndowmentController.{settings_field}.delegate.address` for the field being changed.
7. User is `Endowment.owner` and `EndowmentController.endowment_controller.delegate` and `EndowmentController.{settings_field}.delegate.address` for the field being changed.
8. User is none of the above.
9. Any missing case?

**Comment by SovereignAndrey** [comment] 2023-03-15 08:24
@misicnenad This form is about updating the EndowmentController as a whole, not the individual fields. Therefore the logic / psudocode tp check for whether a user can update/submit this message should look something like:

> ```ts
> if (
>   cw3_multisig_controls_the_endowment_controller_field() &&
>   connected_wallet in Endowment CW3 owner members array 
> ) {
>   create_a_proposal(update_endowment_controller_msg);
> } else if (delegate_address_can_update_endowment_controller(connected_wallet)) {
>   send_direct_to_settings_contract(update_endowment_controller_msg);
> }
> ```

**Comment by misicnenad** [comment] 2023-03-15 10:23
@SovereignAndrey 
What takes precedence when a connected wallet is both member of endowment's CW3 owners array AND is set as the `endowment_controller.delegate.address`? Do we send a proposal or do we send a direct msg?

**Comment by SovereignAndrey** [comment] 2023-03-16 01:06
> @SovereignAndrey 
> What takes precedence when a connected wallet is both member of endowment's CW3 owners array AND is set as the `endowment_controller.delegate.address`? Do we send a proposal or do we send a direct msg?

Excellent question!! I think the delegate would take precedence.

**Comment by misicnenad** [comment] 2023-03-17 09:09
@SovereignAndrey 
Trying to understand the role of `EndowmentController.endowment_controller` field. 

1. What does it, or its subfields, "control" exactly?
2. Let's say this is the controller state:
```ts
EndowmentController = {
  endowment_controller: {
    owner_controlled: false,
    gov_controlled: false,
    modifiable: true,
    delegate: null,
  },
  name: {
    owner_controlled: true,
    gov_controlled: false,
    modifiable: true,
    delegate: null,
  }
  ...
}
```
Notice that `endowment_controller.owner_controlled === false`, but `name.owner_controlled === true`. 
**Can the `name` be modified by the owner then?**

3. Let's now take this state:
```ts
EndowmentController = {
  endowment_controller: {
    delegate: { address: "juno1somejunoaddresswhatever" },
    ...
  },
  name: {
    delegate: null,
  }
  ...
}
```
Now let's say the user who is designated as `endowment_controller.delegate.address` tries to update the `name` field which *has no delegated address*.
**Can they update the field?**

**Comment by SovereignAndrey** [comment] 2023-03-17 09:45
> 1. What does it, or its subfields, "control" exactly?

It controls who can update the EndowmentController struct and if it's modifiable at all. The other fields on the EndowmentController all control who can update (and if even modifiable) other fields on other structs found on the Accounts and AccountsSettingsController contracts. 

> 2. Let's say this is the controller state:
> ```ts
> EndowmentController = {
>   endowment_controller: {
>     owner_controlled: false,
>     gov_controlled: false,
>     modifiable: true,
>     delegate: null,
>   },
>   name: {
>     owner_controlled: true,
>     gov_controlled: false,
>     modifiable: true,
>     delegate: null,
>   }
>   ...
> }
> ```

EndowmentController is locked because we've go no one owning it. 

As for the Name field (found on the Accounts contract Endowment struct. That is modifiable by the Endowment owner multisig (by passing a proposal with an `UpdateEndowmentDetailsMsg` and the name field in there). 

> 3. Let's now take this state:
> ```ts
> EndowmentController = {
>   endowment_controller: {
>     delegate: { address: "juno1somejunoaddresswhatever" },
>     ...
>   },
>   name: {
>     delegate: null,
>   }
>   ...
> }
> ```
> 
> Now let's say the user who is designated as `endowment_controller.delegate.address` tries to update the `name` field which _has no delegated address_. **Can they update the field?**

I think you're confusing updating the permissions of these fields here in the `EndowmentController` struct with updating the fields themselves? Only contract address/delegates set on the `endowment_controller` field of the `EndowmentController` struct are allowed to modify this struct and all it's fields. The ones who are set as owners here are the ones allowed to change those actual values on the respective structs. 

Here's a diagram that will hopefully illustrate the permissions vs field updates setup:
![Endowment Controller permissions logic](https://user-images.githubusercontent.com/85138450/225869824-c82d15ff-c232-4971-9aa8-80e9150ea25f.png)

**Comment by misicnenad** [comment] 2023-03-20 07:08
> > 1. What does it, or its subfields, "control" exactly?
> 
> It controls who can update the EndowmentController struct and if it's modifiable at all. The other fields on the EndowmentController all control who can update (and if even modifiable) other fields on other structs found on the Accounts and AccountsSettingsController contracts.
> 
> > 2. Let's say this is the controller state:
> > 
> > ```ts
> > EndowmentController = {
> >   endowment_controller: {
> >     owner_controlled: false,
> >     gov_controlled: false,
> >     modifiable: true,
> >     delegate: null,
> >   },
> >   name: {
> >     owner_controlled: true,
> >     gov_controlled: false,
> >     modifiable: true,
> >     delegate: null,
> >   }
> >   ...
> > }
> > ```
> 
> EndowmentController is locked, despite being modifiable, because we've got no one owning it in that example.
> 
> As for the Name field (found on the Accounts contract Endowment struct. That is modifiable by the Endowment owner multisig (by passing a proposal with an `UpdateEndowmentDetailsMsg` and the name field in there).
> 
> > 3. Let's now take this state:
> > 
> > ```ts
> > EndowmentController = {
> >   endowment_controller: {
> >     delegate: { address: "juno1somejunoaddresswhatever" },
> >     ...
> >   },
> >   name: {
> >     delegate: null,
> >   }
> >   ...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now let's say the user who is designated as `endowment_controller.delegate.address` tries to update the `name` field which _has no delegated address_. **Can they update the field?**
> 
> I think you're confusing updating the permissions of these fields here in the `EndowmentController` struct with updating the fields themselves? Only contract address/delegates set on the `endowment_controller` field of the `EndowmentController` struct are allowed to modify this struct and all it's fields. The ones who are set as owners here are the ones allowed to change those actual values on the respective structs.
> 
> Here's a diagram that will hopefully illustrate the permissions vs field updates setup: ![Endowment Controller permissions logic](https://user-images.githubusercontent.com/85138450/225869824-c82d15ff-c232-4971-9aa8-80e9150ea25f.png)

In other words, only `endowment_controller` fields are relevant for deciding who is authorized to modify the controller itself, while other fields' flags are to say who is allowed to modify the relevant endowment data, NOT the controller.
Updating the code, testing and reopening the PR.

**Closed** 2023-03-21 07:32 UTC
